### ISSUE TITLE
Custom VictoriaMetrics prometheus url support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [pingcap/tidb-dashboard#1255]
## Bug Report

**What did you do?**

I tried to set VictoriaMetrics select url as prometheus url.

Also isn't applied
```toml
[pd-server]
metric-storage = "http://vm-select.vm:8481/select/0/prometheus"
```

**What did you expect to see?**

`http://vm-select.vm:8481/select/0/prometheus`

**What did you see instead?**

`http://vm-select.vm:8481`

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

TiDB Dashboard Internal Version: 2022.01.17.1
TiDB Dashboard Build Git Hash: e8076b5c79ba
PD Version: v5.4.0

![image](https://user-images.githubusercontent.com/46970457/168496702-e63aa14d-6210-4421-b667-e8aae26a8993.png)
