### ISSUE TITLE
Dashboard can not display the disk info correctly when tiflash is deployed on multiple disks

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tidb-dashboard#1625]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Deploy a cluster with tiflash instance on multiple disks. For example:

```
tiflash_servers:
  - host: 127.0.0.1
    tcp_port: 5040
    http_port: 4540
    flash_service_port: 9540
    flash_proxy_port: 9040
    flash_proxy_status_port: 20040
    metrics_port: 20540
    config:
      storage.main.dir :   [ /DATA/disk1/clusters/tiflash-5040/data, /DATA/disk2/clusters/tiflash-5040/data ]
      storage.main.capacity:   [ 107374182400 ]
```

**What did you expect to see?**

The "Cluster Info" -> "Disks" can display the disk of tiflash correctly

**What did you see instead?**

![image](https://github.com/pingcap/tidb-dashboard/assets/4865550/7dbe87f4-d4bc-4795-be20-d1fca0071084)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

tidb v6.5.5
